foodie:
  minio:
    endpoint: http://192.168.1.11:9000
    accessKey: admin
    secretKey: lkw2468LKW@
    bucket: foodie-images
    publicUrl: http://192.168.1.11:9000/foodie-images
    basePath: upload
    maxSize: 5
    allowedTypes:
      - jpg
      - jpeg
      - png
      - gif
      - webp
