spring:
  # -------------------------
  # 应用名称
  # -------------------------
  application:
    name: foodie-platform-server

  config:
    import: classpath:application-common-base.yml

  # -------------------------
  # 服务器端口
  # -------------------------
server:
  port: 8081
