spring:
  # -------------------------
  # ???????????
  # -------------------------
  profiles:
    active: dev   # ??????? dev

  # -------------------------
  # ????
  # -------------------------
  application:
    name: foodie-platform-server

  # -------------------------
  # ?????
  # -------------------------
server:
    port: 8083

foodie:
  cache:
    merchant-status-ttl-hours: 24

