spring:
  # -------------------------
  # Redis 配置
  # -------------------------
  redis:
    database: 2          # 使用不同的数据库

  config:
    import: classpath:application-dev-common.yml

# -------------------------
# JWT 配置（用户端）
# -------------------------
foodie:
  jwt:
    user-secret-key: ${USER_JWT_SECRET_KEY:foodie-user-20260109-secret-key}
    user-ttl: ${USER_JWT_TTL:7200000}
    user-token-name: ${USER_TOKEN_NAME:user-token}
  upload:
    service-path: user
