spring:
  # -------------------------
  # 应用名称
  # -------------------------
  application:
    name: foodie-merchant-server

  config:
    import: classpath:application-common-base.yml

  # -------------------------
  # 服务器端口
  # -------------------------
server:
  address: 0.0.0.0
  port: 8082

foodie:
  jwt:
    merchant-secret-key: mySecretKey123
    merchant-ttl: 86400000          # 24小时
    merchant-token-name: Authorization
  cache:
    merchant-status-ttl-hours: 24
