spring:
  # -------------------------
  # Redis 配置
  # -------------------------
  redis:
    database: 3         # 使用不同的数据库

  config:
    import: classpath:application-dev-common.yml

# -------------------------
# JWT 配置（商户端）
# -------------------------
foodie:
  jwt:
    merchant-secret-key: ${MERCHANT_JWT_SECRET_KEY:foodie-merchant-20260109-secret-key}
    merchant-ttl: ${MERCHANT_JWT_TTL:7200000}
    merchant-token-name: ${MERCHANT_TOKEN_NAME:merchant-token}
  upload:
    service-path: merchant
